scrape_configs:
  - job_name: 'c3-frontend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['35.198.209.120:80']
        labels:
          application: 'c3-frontend'