name: Remove old artifacts

on:
  push:
    branches: 
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging
  schedule:
    - cron: '0 */2 * * *'

permissions:
  actions: write
  contents: read
  
jobs:
  cleanup_artifacts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Remove old artifacts
      uses: actions/github-script@v6
      with:
        script: |
          const res = await github.rest.actions.listArtifactsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          res.data.artifacts.forEach(async (artifact) => {
            await github.rest.actions.deleteArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: artifact.id,
            });
          });
